language: node_js

node_js:
  - lts/carbon
  - lts/dubnium
  - stable

before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
  - npm install -g greenkeeper-lockfile@1

install:
  - '[[ $TRAVIS_BRANCH == greenkeeper/* ]] && npm install || npm ci'

before_script:
  - greenkeeper-lockfile-update

script:
  - npm test
  - npm run build

after_script:
  - greenkeeper-lockfile-upload

jobs:
  include:
    - stage: deploy
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: master
        script:
          - npm run semantic-release
