name: Release

on:
  push:
    branches: [master]

jobs:
  publish-test:
    uses: ./.github/workflows/pull-request.yml

  publish-npm:
    name: NPM
    needs: [publish-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup Git
        uses: fregante/setup-git-user@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: NPM
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update develop
        run: |
          git checkout develop
          git merge master
          git push origin develop
